enh(main): add an option to automatically create users
twilio/authy-freeradius pull request #9
Opened 2020-05-26 19:52 UTC by benrubson

Hi,

This PR adds a new configuration option : `CreateUser`.
If set to `yes`, Authy users will automatically be created if they do not exist in the Authy account yet (so when they first authenticate).
It's then no more needed to manually add every new user...

Thx 👍 

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2020-05-26 19:54 UTC, benrubson commented
Note that the 2 PDF documentations (_Release Notes_ and _Installation Guide_) could perhaps be updated accordingly.

2020-06-04 20:59 UTC, LucasVidal requested changes
Hey Ben. Thanks for submitting this. I think that you are adding some logic here that may not be applied for all others. I'm not sure that everyone would expect the user to be created if not found. Let me know if I'm mistaken but I would tend to avoid introducing disruptive changes into a shared library.

2020-06-04 21:06 UTC, benrubson commented
Thank you for your first feedback Lucas.

I let you read the change, but you'll notice that I've introduced a new option (disabled by default) to toggle this feature.

This option can be useful in many situations.
Let me give you an example.
Think about a Radius server newly connected to an existing enterprise directory containing thousands of users.
The Radius server runs this `authy-freeradius` plugin to double-authenticate the users.
The administrator of this authentication solution may then be find really useful for the users to automatically be added into his Authy account when they authenticate for the first time, instead of having to add each one of them manually :)

Thank you again 👍

2020-06-04 21:24 UTC, LucasVidal commented
Yes I understand. I still think that adding users should be in a separated moment. Decisions on when to add a user are personal. This means that a user has accepted to enable 2FA. That's why doing that automatically does not make a lot of sense to me. 

Not finding an authy_id typically could be interpreted as "2FA is disabled". If we create the user on demand an implementation could lock users out without knowing that 2fa is being enabled for them. 

I'll bring this PR to the rest of the team if someone disagrees with me, or if I'm missing something. Thanks!

2020-06-04 21:24 UTC, closed without merging

2020-06-04 21:32 UTC, benrubson commented
Think that administrator of the authentication solution could deliberately want to enforce Authy-2FA on the Radius server, to enforce authentication security of the company's employees.

So that for example a user can't login into the VPN of the company if he does not succeed with 2FA.

In this case then, where 2FA is enforced, it is very convenient for the users to automatically be added by the module, to avoid a manual process, painful on large directories...

2020-06-24 22:19 UTC, benrubson commented
> I'll bring this PR to the rest of the team if someone disagrees with me, or if I'm missing something. Thanks!

Hi @LucasVidal, did you manage to share my thoughts about this feature (optional, as toggled by a configuration option) with the rest of the Authy team ? @philnash / @robinske perhaps ?

It's very useful in various companies here, would then really be nice to re-open / re-consider it.

Thank you very much Lucas 👍

Ben

2020-09-16 14:04 UTC, benrubson commented
> I'll bring this PR to the rest of the team if someone disagrees with me, or if I'm missing something. Thanks!

Hi @LucasVidal, 3 months have passed, did you manage to share my thoughts about this feature (optional, as toggled by a configuration option) with the rest of the Authy team ? @philnash / @robinske perhaps ?

It's very useful in various companies here, would then really be nice to re-open / re-consider it.

Thank you very much Lucas 👍

Ben